apiVersion: v1
kind: Service
metadata:
  name: notitia-python-service
spec:
  ports:
  - port: 80
    targetPort: python-port
    protocol: TCP
  selector:
    app: notitia-python
  type: LoadBalancer
