apiVersion: v1
kind: Pod
metadata:
  name: pod-notitia-python
  labels:
    app: notitia-python
spec:
  containers:
  - name: notitia-python
    image: canaantt/notitia-python
    ports:
    - name: python-port
      containerPort: 80
